{
    'name': 'Odoo-Shore POS Sync',
    'summary': """Synchronize data between Shore POS and Odoo.""",
    'description': """Odoo-Shore POS Sync is a connector add-on for Odoo that synchronizes data between Shore POS and Odoo.""",
    'license': 'AGPL-3',
    'author': 'roboes',
    'website': 'https://github.com/roboes/odoo-shorepos-sync',
    'category': 'Connectors',
    'version': '16.0.0.0',
    # 'version': '18.0.0.0',
    'external_dependencies': {
        'python': ['filetype', 'numpy', 'opencv-python'],
    },
    'depends': ['account', 'contacts', 'queue_job', 'product', 'sale_management', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/v16/product_product_form.xml',
        'views/v16/product_product_tree.xml',
        'views/v16/product_template_form.xml',
        'views/v16/product_template_tree.xml',
        'views/v16/views.xml',
        # 'views/v18/product_product_form.xml',
        # 'views/v18/product_product_tree.xml',
        # 'views/v18/product_template_form.xml',
        # 'views/v18/product_template_tree.xml',
        # 'views/v18/views.xml',
    ],
    'assets': {},
    'installable': True,
    'application': True,
    'auto_install': False,
}
